DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS entry;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE entry (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  employee_id INTEGER NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  date_of_birth INT NOT NULL,
  address TEXT NOT NULL,
  phone INTEGER NOT NULL,
  project TEXT NOT NULL,
  hours INTEGER NOT NULL,
  FOREIGN KEY (employee_id) REFERENCES user (id)
);